version: 2

models:
  - name: market_metrics
    columns:
      - name: symbol
        tests:
          - not_null

      - name: window_start
        tests:
          - not_null

      - name: window_end
        tests:
          - not_null

      - name: avg_price
        tests:
          - not_null

      - name: tick_count
        tests:
          - not_null
